gpkg-dev/glibc: system call fix (#45)
+grun improvement

diff --git a/gpkg-dev/glibc/grun b/gpkg-dev/glibc/grun
--- a/gpkg-dev/glibc/grun
+++ b/gpkg-dev/glibc/grun
@@ -1,22 +1,32 @@
 #!/data/data/com.termux/files/usr/bin/bash
 
-# version: 1.2
-# this command allows you to run commands that depend on glibc
-# or run a shell with access to commands from a configured glibc.
+# version: 1.3
+# This script allows you to:
+# - run glibc-based binaries with ld.so.
+# - configure glibc-based binaries to work in Termux.
+# - start a special shell with access to glibc commands.
 
 if [[ -z "$1" ]]; then
-	echo "This command allows you to run commands that depend on glibc"
-	echo "or run a shell with access to commands from a configured glibc."
+	echo "Help message from grun-1.3"
 	echo ""
-	echo "  --shell - launching a customized shell"
+	echo "This script allows you to:"
+	echo " - run glibc-based binaries with ld.so."
+	echo " - configure glibc-based binary to work in Termux."
+	echo " - start a special shell with access to glibc commands."
 	echo ""
-	echo "  --help - print help text from ld.so command"
+	echo "Flags:"
+	echo " --shell - launching a customized shell"
+	echo " --set - binary setup"
+	echo " --help - print help text from ld.so command"
 	echo ""
+	echo "Example: grun [--set] ./binary || grun --shell [gcc -v]"
+	echo "Bur report: https://github.com/termux-pacman/glibc-packages/issues"
 	exit 0
 fi
 
 unset LD_PRELOAD
-export PATH=$PREFIX/glibc/bin:$PATH
+export GLIBC_PREFIX=$PREFIX/glibc
+export PATH=$GLIBC_PREFIX/bin:$PATH
 
 if [ "$1" = "--shell" ]; then
 	if [[ -z "$2" ]]; then
@@ -24,6 +34,29 @@ if [ "$1" = "--shell" ]; then
 	else
 		commands="$@"
 		exec ${commands#* }
+	fi
+elif [ "$1" = "--set" ]; then
+	if [ -z "$2" ]; then
+		echo "Error: binary not specified"
+		exit 1
+	fi
+	if [ ! -f "$2" ]; then
+		echo "Error: binary not found"
+		exit 1
+	fi
+	if $(type patchelf &> /dev/null); then
+		LD_FILE=$(ls $GLIBC_PREFIX/lib/ld-* 2> /dev/null)
+		if [ -n "$LD_FILE" ]; then
+			patchelf --set-rpath $GLIBC_PREFIX/lib \
+				--set-interpreter $LD_FILE \
+				"$2"
+		else
+			echo "Error: interpreter not found in lib directory"
+			exit 1
+		fi
+	else
+		$PREFIX/libexec/termux/command-not-found patchelf
+		exit 1
 	fi
 else
 	exec ld.so $@
