build-cgct.yml: adding `workflow_dispatch`

diff --git a/.github/workflows/build-cgct.yml b/.github/workflows/build-cgct.yml
--- a/.github/workflows/build-cgct.yml
+++ b/.github/workflows/build-cgct.yml
@@ -9,6 +9,11 @@ on:
   pull_request:
     paths:
     - 'cgct/**'
+  workflow_dispatch:
+    inputs:
+      packages:
+        description: "A space-separated names of packages selected for rebuilding"
+        required: true
 
 jobs:
   build:
@@ -22,26 +27,38 @@ jobs:
     - name: Get list cgct packages
       run: |
         mkdir -p "pkgs/PKGBUILDs"
-        if [ ${{ github.event_name }} = "pull_request" ]; then
-          list=$(curl --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s -X GET -G \
-            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" | jq -r '.[] | .filename')
-        else
-          list=$(curl --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s -X GET -G \
-            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}" | jq -r ".files[].filename")
-        fi
-        for i in $list; do
-          il=(${i//// })
-          if [ "${il[0]}" = "cgct" ]; then
-            if [ -d "${il[0]}/${il[1]}" ]; then
-              if [ ! -f pkgs/cgct-need.txt ] || ! $(grep -q '^'${il[1]}'$' pkgs/cgct-need.txt); then
-                echo "${il[1]}" >> pkgs/cgct-need.txt
-                curl -L "https://raw.githubusercontent.com/termux-pacman/glibc-packages/$(git log -n 2 --format=format:%H cgct/${il[1]} | tail -1)/cgct/${il[1]}/PKGBUILD" -o pkgs/PKGBUILDs/${il[1]}
-              fi
-            else
-              echo "${il[1]}" >> pkgs/deleted_cgct_packages.txt
-            fi
+        if [ ${{ github.event_name }} != "workflow_dispatch" ]; then
+          if [ ${{ github.event_name }} = "pull_request" ]; then
+            list=$(curl --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s -X GET -G \
+              "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" | jq -r '.[] | .filename')
+          else
+            list=$(curl --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s -X GET -G \
+              "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}" | jq -r ".files[].filename")
           fi
-        done
+          for i in $list; do
+            il=(${i//// })
+            if [ "${il[0]}" = "cgct" ]; then
+              if [ -d "${il[0]}/${il[1]}" ]; then
+                if [ ! -f pkgs/cgct-need.txt ] || ! $(grep -q "^${il[1]}$" pkgs/cgct-need.txt); then
+                  echo "${il[1]}" >> pkgs/cgct-need.txt
+                  curl -L "https://raw.githubusercontent.com/termux-pacman/glibc-packages/$(git log -n 2 --format=format:%H cgct/${il[1]} | tail -1)/cgct/${il[1]}/PKGBUILD" -o pkgs/PKGBUILDs/${il[1]}
+                fi
+              else
+                echo "${il[1]}" >> pkgs/deleted_cgct_packages.txt
+              fi
+            fi
+          done
+        else
+          for i in ${{ github.event.inputs.packages }}; do
+            if [ ! -d cgct/${i} ]; then
+              echo "Error: package '${i}' not found"
+              exit 1
+            fi
+            if [ ! -f pkgs/cgct-need.txt ] || ! $(grep -q "^${i}$" pkgs/cgct-need.txt); then
+              echo "${i}" >> pkgs/cgct-need.txt
+            fi
+          done
+        fi
     - name: Build cgct packages
       run: |
         sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost
